// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

#include <OB/CORBAServer.h>
#include <hello_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030200L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:Hello/say_hello:1.0
//
void
POA_Hello::_OB_op_say_hello(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    say_hello();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:Hello/shutdown:1.0
//
void
POA_Hello::_OB_op_shutdown(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_postUnmarshal(_ob_up);
    shutdown();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:Hello:1.0
//
::CORBA::Boolean
POA_Hello::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = Hello::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_Hello::_primary_interface(const PortableServer::ObjectId&,
                              PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(Hello::_OB_staticIds()[0]);
}

Hello_ptr
POA_Hello::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    Hello_var result = Hello::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_Hello::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                    const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_Hello(poa, oid, this);
}

void
POA_Hello::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "say_hello",
        "shutdown"
    };
    static const ::CORBA::ULong _ob_numNames = 2;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // say_hello
        _OB_op_say_hello(_ob_up);
        return;

    case 1: // shutdown
        _OB_op_shutdown(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:Hello:1.0
//
OBDirectStubImpl_Hello::OBDirectStubImpl_Hello(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:Hello/say_hello:1.0
//
void
OBDirectStubImpl_Hello::say_hello()
{
    OB::InvocationHandler _ob_handler(this, "say_hello");
    dynamic_cast<POA_Hello*>(_ob_servant_) -> say_hello();
}

//
// IDL:Hello/shutdown:1.0
//
void
OBDirectStubImpl_Hello::shutdown()
{
    OB::InvocationHandler _ob_handler(this, "shutdown");
    dynamic_cast<POA_Hello*>(_ob_servant_) -> shutdown();
}
