// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

#ifndef ___PIDemo_skel_h__
#define ___PIDemo_skel_h__

#include <PIDemo.h>


#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030200L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:PIDemo:1.0
//
class POA_PIDemo : virtual public PortableServer::ServantBase
{
    POA_PIDemo(const POA_PIDemo&);
    void operator=(const POA_PIDemo&);

protected:

    //
    // IDL:PIDemo/noargs:1.0
    //
    void _OB_op_noargs(OB::Upcall_ptr);

    //
    // IDL:PIDemo/noargs_oneway:1.0
    //
    void _OB_op_noargs_oneway(OB::Upcall_ptr);

    //
    // IDL:PIDemo/noargs_return:1.0
    //
    void _OB_op_noargs_return(OB::Upcall_ptr);

    //
    // IDL:PIDemo/withargs:1.0
    //
    void _OB_op_withargs(OB::Upcall_ptr);

    //
    // IDL:PIDemo/systemexception:1.0
    //
    void _OB_op_systemexception(OB::Upcall_ptr);

    //
    // IDL:PIDemo/userexception:1.0
    //
    void _OB_op_userexception(OB::Upcall_ptr);

    //
    // IDL:PIDemo/switch_to_static_impl:1.0
    //
    void _OB_op_switch_to_static_impl(OB::Upcall_ptr);

    //
    // IDL:PIDemo/switch_to_dynamic_impl:1.0
    //
    void _OB_op_switch_to_dynamic_impl(OB::Upcall_ptr);

    //
    // IDL:PIDemo/call_other_impl:1.0
    //
    void _OB_op_call_other_impl(OB::Upcall_ptr);

    //
    // IDL:PIDemo/deactivate:1.0
    //
    void _OB_op_deactivate(OB::Upcall_ptr);

public:

    POA_PIDemo() { }

    virtual ::CORBA::Boolean _is_a(const char*)
        throw(::CORBA::SystemException);

    virtual ::CORBA::RepositoryId _primary_interface(
        const PortableServer::ObjectId&,
        PortableServer::POA_ptr);

    PIDemo_ptr _this();

    virtual OB::DirectStubImpl_ptr _OB_createDirectStubImpl(
        PortableServer::POA_ptr,
        const PortableServer::ObjectId&);
    virtual void _OB_dispatch(OB::Upcall_ptr);

    //
    // IDL:PIDemo/noargs:1.0
    //
    virtual void noargs()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/noargs_oneway:1.0
    //
    virtual void noargs_oneway()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/noargs_return:1.0
    //
    virtual char* noargs_return()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/withargs:1.0
    //
    virtual void withargs(const char* param1,
                          char*& param2,
                          ::CORBA::String_out param3)
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/systemexception:1.0
    //
    virtual void systemexception()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/userexception:1.0
    //
    virtual void userexception()
        throw(PIDemo::User,
              ::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/switch_to_static_impl:1.0
    //
    virtual void switch_to_static_impl()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/switch_to_dynamic_impl:1.0
    //
    virtual void switch_to_dynamic_impl()
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/call_other_impl:1.0
    //
    virtual void call_other_impl(::CORBA::Short level)
        throw(::CORBA::SystemException) = 0;

    //
    // IDL:PIDemo/deactivate:1.0
    //
    virtual void deactivate()
        throw(::CORBA::SystemException) = 0;
};

//
// IDL:PIDemo:1.0
//
class OBDirectStubImpl_PIDemo : virtual public OBStubImpl_PIDemo,
                                virtual public OB::DirectStubImpl
{
    OBDirectStubImpl_PIDemo(const OBDirectStubImpl_PIDemo&);
    void operator=(const OBDirectStubImpl_PIDemo&);

protected:

#ifdef HAVE_VCPLUSPLUS_BUGS

    OBDirectStubImpl_PIDemo() { }

#endif

    OBDirectStubImpl_PIDemo(PortableServer::POA_ptr,
                            const PortableServer::ObjectId&,
                            PortableServer::ServantBase*);

    friend class POA_PIDemo;

public:

    //
    // IDL:PIDemo/noargs:1.0
    //
    virtual void noargs();

    //
    // IDL:PIDemo/noargs_oneway:1.0
    //
    virtual void noargs_oneway();

    //
    // IDL:PIDemo/noargs_return:1.0
    //
    virtual char* noargs_return();

    //
    // IDL:PIDemo/withargs:1.0
    //
    virtual void withargs(const char* param1,
                          char*& param2,
                          ::CORBA::String_out param3);

    //
    // IDL:PIDemo/systemexception:1.0
    //
    virtual void systemexception();

    //
    // IDL:PIDemo/userexception:1.0
    //
    virtual void userexception();

    //
    // IDL:PIDemo/switch_to_static_impl:1.0
    //
    virtual void switch_to_static_impl();

    //
    // IDL:PIDemo/switch_to_dynamic_impl:1.0
    //
    virtual void switch_to_dynamic_impl();

    //
    // IDL:PIDemo/call_other_impl:1.0
    //
    virtual void call_other_impl(::CORBA::Short level);

    //
    // IDL:PIDemo/deactivate:1.0
    //
    virtual void deactivate();
};

#endif
