// **********************************************************************
//
// Generated by the ORBacus IDL-to-C++ Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

#include <OB/CORBAServer.h>
#include <PIDemo_skel.h>

#ifndef OB_INTEGER_VERSION
#   error No ORBacus version defined! Is <OB/CORBA.h> included?
#endif

#ifndef OB_NO_VERSION_CHECK
#   if (OB_INTEGER_VERSION != 4030200L)
#       error ORBacus version mismatch!
#   endif
#endif

//
// IDL:PIDemo/noargs:1.0
//
void
POA_PIDemo::_OB_op_noargs(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    noargs();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/noargs_oneway:1.0
//
void
POA_PIDemo::_OB_op_noargs_oneway(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    noargs_oneway();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/noargs_return:1.0
//
void
POA_PIDemo::_OB_op_noargs_return(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    OB::ParameterDesc _ob_retDesc =
    {
        0, ::CORBA::_tc_string, 0, 0 /*in*/
    };
    _OB_setArgDesc(_ob_up, 0, 0, &_ob_retDesc, 0, 0);
    _OB_postUnmarshal(_ob_up);
    ::CORBA::String_var _ob_r = noargs_return();
    _ob_retDesc.param = _ob_r.inout();
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_out -> write_string(_ob_r.in());
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/withargs:1.0
//
void
POA_PIDemo::_OB_op_withargs(OB::Upcall_ptr _ob_up)
{
    OB::StrForStruct _ob_a0;
    OB::StrForStruct _ob_a1;
    ::CORBA::String_var _ob_a2;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    _ob_a0 = _ob_in -> read_string();
    _ob_a1 = _ob_in -> read_string();
    OB::ParameterDesc _ob_desc[] =
    {
        {
            (void*)_ob_a0.in(), ::CORBA::_tc_string, 0, 0 /*in*/
        },
        {
            (void*)_ob_a1.in(), ::CORBA::_tc_string, 0, 2 /*inout*/
        },
        {
            0, ::CORBA::_tc_string, 0, 1 /*out*/
        }
    };
    _OB_setArgDesc(_ob_up, _ob_desc, 3, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    withargs(_ob_a0, _ob_a1.inout(), _ob_a2.out());
    _ob_desc[1].param = _ob_a1.inout();
    _ob_desc[2].param = _ob_a2.inout();
    _OB_postinvoke(_ob_up);
    OB::OutputStreamImpl* _ob_out = _OB_preMarshal(_ob_up);
    _ob_out -> write_string(_ob_a1.in());
    _ob_out -> write_string(_ob_a2.in());
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/systemexception:1.0
//
void
POA_PIDemo::_OB_op_systemexception(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    systemexception();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/userexception:1.0
//
void
POA_PIDemo::_OB_op_userexception(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    ::CORBA::TypeCode_ptr _ob_exceptions[] =
    {
        PIDemo::_tc_User
    };
    _OB_setArgDesc(_ob_up, 0, 0, 0, _ob_exceptions, 1);
    _OB_postUnmarshal(_ob_up);
    userexception();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/switch_to_static_impl:1.0
//
void
POA_PIDemo::_OB_op_switch_to_static_impl(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    switch_to_static_impl();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/switch_to_dynamic_impl:1.0
//
void
POA_PIDemo::_OB_op_switch_to_dynamic_impl(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    switch_to_dynamic_impl();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/call_other_impl:1.0
//
void
POA_PIDemo::_OB_op_call_other_impl(OB::Upcall_ptr _ob_up)
{
    ::CORBA::Short _ob_a0;
    OB::InputStreamImpl* _ob_in = _OB_preUnmarshal(_ob_up);
    _ob_a0 = _ob_in -> read_short();
    OB::ParameterDesc _ob_desc[] =
    {
        {
            &_ob_a0, ::CORBA::_tc_short, 0, 0 /*in*/
        }
    };
    _OB_setArgDesc(_ob_up, _ob_desc, 1, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    call_other_impl(_ob_a0);
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo/deactivate:1.0
//
void
POA_PIDemo::_OB_op_deactivate(OB::Upcall_ptr _ob_up)
{
    _OB_preUnmarshal(_ob_up);
    _OB_setArgDesc(_ob_up, 0, 0, 0, 0, 0);
    _OB_postUnmarshal(_ob_up);
    deactivate();
    _OB_postinvoke(_ob_up);
    _OB_preMarshal(_ob_up);
    _OB_postMarshal(_ob_up);
}

//
// IDL:PIDemo:1.0
//
::CORBA::Boolean
POA_PIDemo::_is_a(const char* type)
    throw(::CORBA::SystemException)
{
    const char** _ob_ids = PIDemo::_OB_staticIds();
    for(::CORBA::ULong _ob_i = 0; _ob_ids[_ob_i] != 0; ++_ob_i)
        if(strcmp(type, _ob_ids[_ob_i]) == 0)
            return true;

    return false;
}

::CORBA::RepositoryId
POA_PIDemo::_primary_interface(const PortableServer::ObjectId&,
                               PortableServer::POA_ptr)
{
    return ::CORBA::string_dup(PIDemo::_OB_staticIds()[0]);
}

PIDemo_ptr
POA_PIDemo::_this()
{
    ::CORBA::Object_var obj = _OB_createReference();
    PIDemo_var result = PIDemo::_narrow(obj);
    return result._retn();
}

OB::DirectStubImpl_ptr
POA_PIDemo::_OB_createDirectStubImpl(PortableServer::POA_ptr poa,
                                     const PortableServer::ObjectId& oid)
{
    return new OBDirectStubImpl_PIDemo(poa, oid, this);
}

void
POA_PIDemo::_OB_dispatch(OB::Upcall_ptr _ob_up)
{
    static const char* _ob_names[] =
    {
        "call_other_impl",
        "deactivate",
        "noargs",
        "noargs_oneway",
        "noargs_return",
        "switch_to_dynamic_impl",
        "switch_to_static_impl",
        "systemexception",
        "userexception",
        "withargs"
    };
    static const ::CORBA::ULong _ob_numNames = 10;

    switch(_OB_findOperation(_ob_up, _ob_names, _ob_numNames))
    {
    case 0: // call_other_impl
        _OB_op_call_other_impl(_ob_up);
        return;

    case 1: // deactivate
        _OB_op_deactivate(_ob_up);
        return;

    case 2: // noargs
        _OB_op_noargs(_ob_up);
        return;

    case 3: // noargs_oneway
        _OB_op_noargs_oneway(_ob_up);
        return;

    case 4: // noargs_return
        _OB_op_noargs_return(_ob_up);
        return;

    case 5: // switch_to_dynamic_impl
        _OB_op_switch_to_dynamic_impl(_ob_up);
        return;

    case 6: // switch_to_static_impl
        _OB_op_switch_to_static_impl(_ob_up);
        return;

    case 7: // systemexception
        _OB_op_systemexception(_ob_up);
        return;

    case 8: // userexception
        _OB_op_userexception(_ob_up);
        return;

    case 9: // withargs
        _OB_op_withargs(_ob_up);
        return;
    }

    _OB_dispatchBase(_ob_up);
}

//
// IDL:PIDemo:1.0
//
OBDirectStubImpl_PIDemo::OBDirectStubImpl_PIDemo(
    PortableServer::POA_ptr poa,
    const PortableServer::ObjectId& oid,
    PortableServer::ServantBase* servant)
#ifdef HAVE_VCPLUSPLUS_BUGS
{
    _ob_initialize(poa, oid, servant);
}
#else
    : OB::DirectStubImpl(poa, oid, servant)
{
}
#endif

//
// IDL:PIDemo/noargs:1.0
//
void
OBDirectStubImpl_PIDemo::noargs()
{
    OB::InvocationHandler _ob_handler(this, "noargs");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> noargs();
}

//
// IDL:PIDemo/noargs_oneway:1.0
//
void
OBDirectStubImpl_PIDemo::noargs_oneway()
{
    OB::InvocationHandler _ob_handler(this, "noargs_oneway");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> noargs_oneway();
}

//
// IDL:PIDemo/noargs_return:1.0
//
char*
OBDirectStubImpl_PIDemo::noargs_return()
{
    OB::InvocationHandler _ob_handler(this, "noargs_return");
    return dynamic_cast<POA_PIDemo*>(_ob_servant_) -> noargs_return();
}

//
// IDL:PIDemo/withargs:1.0
//
void
OBDirectStubImpl_PIDemo::withargs(const char* _ob_a0,
                                  char*& _ob_a1,
                                  ::CORBA::String_out _ob_a2)
{
    OB::InvocationHandler _ob_handler(this, "withargs");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> withargs(_ob_a0, _ob_a1, _ob_a2);
}

//
// IDL:PIDemo/systemexception:1.0
//
void
OBDirectStubImpl_PIDemo::systemexception()
{
    OB::InvocationHandler _ob_handler(this, "systemexception");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> systemexception();
}

//
// IDL:PIDemo/userexception:1.0
//
void
OBDirectStubImpl_PIDemo::userexception()
{
    OB::InvocationHandler _ob_handler(this, "userexception");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> userexception();
}

//
// IDL:PIDemo/switch_to_static_impl:1.0
//
void
OBDirectStubImpl_PIDemo::switch_to_static_impl()
{
    OB::InvocationHandler _ob_handler(this, "switch_to_static_impl");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> switch_to_static_impl();
}

//
// IDL:PIDemo/switch_to_dynamic_impl:1.0
//
void
OBDirectStubImpl_PIDemo::switch_to_dynamic_impl()
{
    OB::InvocationHandler _ob_handler(this, "switch_to_dynamic_impl");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> switch_to_dynamic_impl();
}

//
// IDL:PIDemo/call_other_impl:1.0
//
void
OBDirectStubImpl_PIDemo::call_other_impl(::CORBA::Short _ob_a0)
{
    OB::InvocationHandler _ob_handler(this, "call_other_impl");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> call_other_impl(_ob_a0);
}

//
// IDL:PIDemo/deactivate:1.0
//
void
OBDirectStubImpl_PIDemo::deactivate()
{
    OB::InvocationHandler _ob_handler(this, "deactivate");
    dynamic_cast<POA_PIDemo*>(_ob_servant_) -> deactivate();
}
